
services:
  php-apache:
    build: ./backend
    container_name: webdiary-php
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  nextjs:
    build: ./frontend
    container_name: webdiary-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - php-apache

  mariadb:
    image: mariadb:10.5
    container_name: webdiary-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdiary
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db_data:
